// tslint:disable
/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Employee Entity
 * @export
 * @interface Employee
 */
export interface Employee {
    /**
     * @type {string}
     * @memberof Employee
     */
    employeeId: string;
    /**
     * First Name
     * @type {string}
     * @memberof Employee
     */
    firstName: string;
    /**
     * Last Name
     * @type {string}
     * @memberof Employee
     */
    lastName: string;
    /**
     * Phone number in integer with no special characters.  Leaving space with 0 for special code.
     * @type {number}
     * @memberof Employee
     */
    phoneNumber: number;
    /**
     * @type {string}
     * @memberof Employee
     */
    email: string;
    /**
     * Address given by a geolocation string
     * @type {string}
     * @memberof Employee
     */
    address?: string | null;
}
