// tslint:disable
/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Item Entity
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * @type {string}
     * @memberof Item
     */
    itemId: string;
    /**
     * Product Associated with Transaction.
     * @type {string}
     * @memberof Item
     */
    productId: string;
    /**
     * Transaction asociated with this item.
     * @type {string}
     * @memberof Item
     */
    transactionId?: string | null;
    /**
     * Added in the backend.
     * @type {string}
     * @memberof Item
     */
    dateAdded?: string;
    /**
     * Wearhouse associated with this transaction.
     * @type {number}
     * @memberof Item
     */
    wearehouseId?: number;
    /**
     * Number or quantity of a given product.This in the unit of the   product itself.
     * @type {number}
     * @memberof Item
     */
    quantity: number;
}
