// tslint:disable
/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Product Entity
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * @type {string}
     * @memberof Product
     */
    productId: string;
    /**
     * @type {string}
     * @memberof Product
     */
    name: string;
    /**
     * @type {string}
     * @memberof Product
     */
    summary?: string | null;
    /**
     * This is on the wearhouse currency like dollar, or equatorian peso.
     * @type {number}
     * @memberof Product
     */
    price: number;
    /**
     * Units that the price is made on. Like L, kg, package, etc.
     * @type {string}
     * @memberof Product
     */
    unit: string;
}
