// tslint:disable
/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Transaction Entity
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * @type {string}
     * @memberof Transaction
     */
    transactionId: string;
    /**
     * Date and time when this transaction finished. Can be dummy for creation.
     * @type {string}
     * @memberof Transaction
     */
    date: string;
    /**
     * Coordinate of where each transaction took place.
     * @type {string}
     * @memberof Transaction
     */
    location?: string | null;
    /**
     * Id of the employee who made this transaction.
     * @type {string}
     * @memberof Transaction
     */
    employeeId: string;
    /**
     * Has this transaction been verified by admi.
     * @type {boolean}
     * @memberof Transaction
     */
    verified: boolean;
    /**
     * Id the of the client beins sold to.
     * @type {string}
     * @memberof Transaction
     */
    clientId?: string | null;
    /**
     * The total of the items selected.This will be computed in the back end.!--  Can be dummy when creating.
     * @type {number}
     * @memberof Transaction
     */
    total: number;
}
