// tslint:disable
/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI } from '../runtime';
import {
    Admi,
} from '../models';

export interface ApiAdmiIdDeleteRequest {
    id: string | null;
}

export interface ApiAdmiIdGetRequest {
    id: string | null;
}

export interface ApiAdmiPostRequest {
    admi?: Admi;
}

export interface ApiAdmiPutRequest {
    admi?: Admi;
}

/**
 * no description
 */
export class AdmiApi extends BaseAPI {

    /**
     * Deletes a Admi entity by its id. Valid employeeId required.
     */
    apiAdmiIdDelete = ({ id }: ApiAdmiIdDeleteRequest): Observable<void> => {
        throwIfNullOrUndefined(id, 'apiAdmiIdDelete');

        return this.request<void>({
            path: '/api/Admi/{id}'.replace('{id}', encodeURI(id)),
            method: 'DELETE',
        });
    };

    /**
     * Gets a Admi entity by its id.
     */
    apiAdmiIdGet = ({ id }: ApiAdmiIdGetRequest): Observable<Admi> => {
        throwIfNullOrUndefined(id, 'apiAdmiIdGet');

        return this.request<Admi>({
            path: '/api/Admi/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        });
    };

    /**
     * Updates a given Admi entity. Valid admiId required.
     */
    apiAdmiPost = ({ admi }: ApiAdmiPostRequest): Observable<void> => {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            path: '/api/Admi',
            method: 'POST',
            headers,
            body: admi,
        });
    };

    /**
     * Adds a new Admi entity with dummy id and returns same Admi enity BUT with   updated id.
     */
    apiAdmiPut = ({ admi }: ApiAdmiPutRequest): Observable<Admi> => {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Admi>({
            path: '/api/Admi',
            method: 'PUT',
            headers,
            body: admi,
        });
    };

}
