// tslint:disable
/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI } from '../runtime';
import {
    Supplier,
} from '../models';

export interface ApiSupplierIdDeleteRequest {
    id: string | null;
}

export interface ApiSupplierIdGetRequest {
    id: string | null;
}

export interface ApiSupplierPostRequest {
    supplier?: Supplier;
}

export interface ApiSupplierPutRequest {
    supplier?: Supplier;
}

/**
 * no description
 */
export class SupplierApi extends BaseAPI {

    /**
     */
    apiSupplierIdDelete = ({ id }: ApiSupplierIdDeleteRequest): Observable<void> => {
        throwIfNullOrUndefined(id, 'apiSupplierIdDelete');

        return this.request<void>({
            path: '/api/Supplier/{id}'.replace('{id}', encodeURI(id)),
            method: 'DELETE',
        });
    };

    /**
     */
    apiSupplierIdGet = ({ id }: ApiSupplierIdGetRequest): Observable<Supplier> => {
        throwIfNullOrUndefined(id, 'apiSupplierIdGet');

        return this.request<Supplier>({
            path: '/api/Supplier/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        });
    };

    /**
     */
    apiSupplierPost = ({ supplier }: ApiSupplierPostRequest): Observable<void> => {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            path: '/api/Supplier',
            method: 'POST',
            headers,
            body: supplier,
        });
    };

    /**
     */
    apiSupplierPut = ({ supplier }: ApiSupplierPutRequest): Observable<void> => {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            path: '/api/Supplier',
            method: 'PUT',
            headers,
            body: supplier,
        });
    };

}
