// tslint:disable
/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, encodeURI } from '../runtime';
import {
    Wearhouse,
} from '../models';

export interface ApiWearhouseIdDeleteRequest {
    id: string | null;
}

export interface ApiWearhouseIdGetRequest {
    id: string | null;
}

export interface ApiWearhousePostRequest {
    wearhouse?: Wearhouse;
}

export interface ApiWearhousePutRequest {
    wearhouse?: Wearhouse;
}

/**
 * no description
 */
export class WearhouseApi extends BaseAPI {

    /**
     */
    apiWearhouseIdDelete = ({ id }: ApiWearhouseIdDeleteRequest): Observable<void> => {
        throwIfNullOrUndefined(id, 'apiWearhouseIdDelete');

        return this.request<void>({
            path: '/api/Wearhouse/{id}'.replace('{id}', encodeURI(id)),
            method: 'DELETE',
        });
    };

    /**
     */
    apiWearhouseIdGet = ({ id }: ApiWearhouseIdGetRequest): Observable<Wearhouse> => {
        throwIfNullOrUndefined(id, 'apiWearhouseIdGet');

        return this.request<Wearhouse>({
            path: '/api/Wearhouse/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        });
    };

    /**
     */
    apiWearhousePost = ({ wearhouse }: ApiWearhousePostRequest): Observable<void> => {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            path: '/api/Wearhouse',
            method: 'POST',
            headers,
            body: wearhouse,
        });
    };

    /**
     */
    apiWearhousePut = ({ wearhouse }: ApiWearhousePutRequest): Observable<void> => {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            path: '/api/Wearhouse',
            method: 'PUT',
            headers,
            body: wearhouse,
        });
    };

}
