// tslint:disable
/**
 * ToDo API
 * A simple example ASP.NET Core Web API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI } from '../runtime';
import {
    WeatherForecast,
} from '../models';

/**
 * no description
 */
export class WeatherForecastApi extends BaseAPI {

    /**
     */
    apiWeatherForecastGet = (): Observable<Array<WeatherForecast>> => {
        return this.request<Array<WeatherForecast>>({
            path: '/api/WeatherForecast',
            method: 'GET',
        });
    };

}
